!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 200.0
  P2: 400.0
  correlation_window_size: 21
  disp12MaxDiff: 0
  disparity_range: 80
  fullDP: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 200.0
      P2: 400.0
      correlation_window_size: 21
      disp12MaxDiff: 0
      disparity_range: 80
      fullDP: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 38
      prefilter_size: 15
      speckle_range: 28
      speckle_size: 921
      state: true
      stereo_algorithm: 0
      texture_threshold: 2300
      type: ''
      uniqueness_ratio: 3.0
    state: []
  min_disparity: 0
  prefilter_cap: 38
  prefilter_size: 15
  speckle_range: 28
  speckle_size: 921
  stereo_algorithm: 0
  texture_threshold: 2300
  uniqueness_ratio: 3.0
state: []
